const app = document.getElementById('app');
const GOOGLE_CLIENT_ID = '882163697172-d3d0e5hbog9sp23dcd1cmnvjgjd7o7of.apps.googleusercontent.com';
const API_BASE_URL = `http://${location.hostname || 'localhost'}:8080/api`;
const CATEGORIES = ['Electronics','Wallet / Purse','Keys','Bottle','Books / Stationery','Clothing','Cards / ID','Accessories','Other'];
const COLORS = ['Black','White','Grey','Blue','Red','Green','Yellow','Brown','Silver','Gold','Multicolor','Other'];
const LOCATIONS = ['School of Arts and Sciences (SAS)','SEAS','University Centre (UC)','Student Lounge','Silent Study Area','Multipurpose Hall (MPH)','Futsal Court','Cafeteria','Other / Not listed'];
const demoItems = [
  {id:'demo-found-1',type:'FOUND',title:'Black Wallet',category:'Wallet / Purse',color:'Black',location:'Silent Study Area',date:'26 Aug 2026',status:'Active',description:'Black leather wallet found near the reading area.'},
  {id:'demo-lost-2',type:'LOST',title:'Silver Water Bottle',category:'Bottle',color:'Silver',location:'Futsal Court',date:'25 Aug 2026',status:'Active',description:'Metallic silver bottle with a small sticker near the base.'},
  {id:'demo-found-3',type:'FOUND',title:'Blue Umbrella',category:'Accessories',color:'Blue',location:'SAS',date:'24 Aug 2026',status:'Active',description:'Foldable blue umbrella found near the entrance.'}
];
let currentUser = JSON.parse(localStorage.getItem('lf_user') || 'null');
let activePage = location.hash.slice(1) || (currentUser ? 'dashboard' : 'login');
let apiItems = [], backendAvailable = false, googleReady = false, debounce;
const esc = (value='') => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const options = values => values.map(value => `<option value="${esc(value)}">${esc(value)}</option>`).join('');
const items = () => backendAvailable ? apiItems : demoItems;
const saveUser = user => { currentUser = user; localStorage.setItem('lf_user', JSON.stringify(user)); };
function navigate(page){ activePage = page; location.hash = page; render(); }
function logout(){ window.google?.accounts?.id?.disableAutoSelect(); localStorage.removeItem('lf_user'); currentUser = null; navigate('login'); }
function dateText(value){ const date = new Date(value); return Number.isNaN(date.valueOf()) ? value || 'Date unavailable' : date.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}); }
function displayItem(item,type){ return {id:`${type.toLowerCase()}-${item.id}`,serverId:item.id,type,title:item.itemName || 'Untitled item',category:item.category || 'Other',color:item.color || 'Not specified',location:item.location || 'Not specified',date:dateText(item.dateTime),status:item.status || 'Active',description:item.description || 'No description provided.',imageUrl:item.imageUrl || ''}; }
async function api(path, config={}){ const response = await fetch(`${API_BASE_URL}${path}`,{headers:{'Content-Type':'application/json'},...config}); if(!response.ok) throw new Error(`API error ${response.status}`); return response.status === 204 ? null : response.json(); }
async function loadItems(){ try{const [lost,found] = await Promise.all([api('/lost-items'),api('/found-items')]);apiItems=[...lost.map(i=>displayItem(i,'LOST')),...found.map(i=>displayItem(i,'FOUND'))];backendAvailable=true;}catch(error){backendAvailable=false;} }
function status(){return backendAvailable?'<span class="api-status online">● Live API</span>':'<span class="api-status demo">● Demo data</span>';}
function shell(content,title){return `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">LF</div><div>Lost & Found<span>Campus platform</span></div></div><nav>${nav('dashboard','⌂ Dashboard')}${nav('browse','⌕ Browse & Search')}${nav('report-lost','＋ Report Lost')}${nav('report-found','＋ Report Found')}${nav('reports','▣ My Reports')}${nav('settings','⚙ Settings')}</nav><div class="sidebar-bottom"><button onclick="logout()">↪ Log out</button></div></aside><main class="main"><header class="topbar"><button class="mobile-menu" onclick="document.getElementById('sidebar').classList.toggle('open')">☰</button><div><div class="eyebrow">Campus Lost & Found</div><h1>${esc(title)}</h1></div><div><button class="avatar" onclick="navigate('settings')">${esc((currentUser?.name||'S')[0].toUpperCase())}</button></div></header><section class="content">${content}</section></main></div>`;}
function nav(page,label){return `<button class="${activePage===page?'active':''}" onclick="navigate('${page}')">${label}</button>`;}
function card(item){return `<article class="item-card"><div class="item-image">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="${esc(item.title)}">`:item.type==='LOST'?'?':'✓'}</div><div class="item-info"><div class="card-top"><span class="badge ${item.type.toLowerCase()}">${item.type}</span><span class="muted">${esc(item.date)}</span></div><h3>${esc(item.title)}</h3><p>${esc(item.category)} · ${esc(item.location)}</p><div class="card-bottom"><span class="status">${esc(item.status)}</span><button class="text-btn" onclick="navigate('item-${encodeURIComponent(item.id)}')">View details →</button></div></div></article>`;}
function dashboard(){const all=items();return shell(`<div class="hero"><div><span class="badge neutral">Welcome back</span><h2>Find it. Report it. Return it.</h2><p>Report and retrieve lost or found campus items in one place.</p></div><div class="hero-actions"><button class="btn primary" onclick="navigate('report-lost')">Report Lost</button><button class="btn secondary" onclick="navigate('report-found')">Report Found</button></div></div><div class="search-hero"><div><span class="eyebrow">Search retrieval</span><h3>Looking for something?</h3><p class="dsa-note">Found-item search uses the supplied normalizer and prefix trie.</p></div><div class="search-row"><input id="home-search" placeholder="Search e.g. black wallet"/><button class="btn primary" onclick="searchHome()">Search</button></div></div><div class="stats"><div class="stat"><span>Active reports</span><strong>${all.filter(i=>i.status==='Active').length}</strong></div><div class="stat"><span>Found reports</span><strong>${all.filter(i=>i.type==='FOUND').length}</strong></div><div class="stat"><span>Lost reports</span><strong>${all.filter(i=>i.type==='LOST').length}</strong></div></div><div class="section-heading"><h3>Recent reports</h3><div>${status()} <button class="text-btn" onclick="navigate('browse')">View all →</button></div></div><div class="item-grid">${all.slice(0,3).map(card).join('')||empty('No reports yet','Be the first to add an item.')}</div>`,'Dashboard');}
function searchHome(){localStorage.setItem('lf_query',document.getElementById('home-search').value);navigate('browse');}
function browse(){const query=localStorage.getItem('lf_query')||'';return shell(`<div class="page-intro"><span class="eyebrow">Search & retrieval</span><h2>Browse reports</h2><p>Keyword, category, color, location, and date filters. ${status()}</p></div><div class="filter-bar"><input id="query" value="${esc(query)}" placeholder="Search item, category, or location" oninput="queueFilter()"><select id="type" onchange="filterItems()"><option value="">All types</option><option>LOST</option><option>FOUND</option></select><select id="category" onchange="filterItems()"><option value="">All categories</option>${options(CATEGORIES)}</select><select id="color" onchange="filterItems()"><option value="">All colors</option>${options(COLORS)}</select><select id="location" onchange="filterItems()"><option value="">All locations</option>${options(LOCATIONS)}</select><input id="start" type="date" onchange="filterItems()"><input id="end" type="date" onchange="filterItems()"></div><p id="algorithm" class="dsa-note"></p><div id="results" class="item-grid"></div>`,'Browse & Search');}
function queueFilter(){clearTimeout(debounce);debounce=setTimeout(filterItems,200);}
function same(a,b){return a.serverId===b.serverId&&a.type===b.type;}
async function filterItems(){const results=document.getElementById('results');if(!results)return;const f={q:(document.getElementById('query').value||'').trim().toLowerCase(),type:document.getElementById('type').value,category:document.getElementById('category').value,color:document.getElementById('color').value,location:document.getElementById('location').value,start:document.getElementById('start').value,end:document.getElementById('end').value};let visible=items(),found=visible.filter(i=>i.type==='FOUND'),algorithms=[];try{if(backendAvailable&&f.type!=='LOST'){if(f.q){const matches=(await api(`/found-items/search?query=${encodeURIComponent(f.q)}&prefix=true`)).map(i=>displayItem(i,'FOUND'));found=found.filter(i=>matches.some(m=>same(i,m)));algorithms.push('normalized trie prefix search');}if(f.category){const matches=(await api(`/found-items/category/${encodeURIComponent(f.category)}`)).map(i=>displayItem(i,'FOUND'));found=found.filter(i=>matches.some(m=>same(i,m)));algorithms.push('hash-table category lookup');}if(f.start&&f.end){const matches=(await api(`/found-items/date-range?start=${encodeURIComponent(f.start+'T00:00:00')}&end=${encodeURIComponent(f.end+'T23:59:59')}`)).map(i=>displayItem(i,'FOUND'));found=found.filter(i=>matches.some(m=>same(i,m)));algorithms.push('binary date-range search');}visible=[...visible.filter(i=>i.type!=='FOUND'),...found];}}catch(error){backendAvailable=false;visible=demoItems;}const filtered=visible.filter(i=>{const text=`${i.title} ${i.category} ${i.location} ${i.description}`.toLowerCase();return(!f.q||text.includes(f.q))&&(!f.type||i.type===f.type)&&(!f.category||i.category===f.category)&&(!f.color||i.color===f.color)&&(!f.location||i.location===f.location);});document.getElementById('algorithm').textContent=algorithms.length?`Using: ${algorithms.join(' · ')}.`:backendAvailable?'Use a keyword, found-item category, or full date range to use a backend index.':'Backend unavailable — using local demo filters.';results.innerHTML=filtered.length?filtered.map(card).join(''):empty('No matching reports','Try a broader keyword or remove a filter.');}
function reportForm(type){const lost=type==='LOST';return shell(`<div class="form-wrap"><div class="page-intro"><span class="eyebrow">${lost?'Lost item':'Found item'}</span><h2>Report ${lost?'a lost':'a found'} item</h2></div><form class="form-card" onsubmit="submitReport(event,'${type}')"><div class="form-section"><h3>Basic information</h3><div class="two-col"><label>Item name *<input required name="title" placeholder="e.g. Black wallet"></label><label>Category *<select required name="category"><option value="">Select category</option>${options(CATEGORIES)}</select></label></div><div class="two-col"><label>Color *<select required name="color"><option value="">Select color</option>${options(COLORS)}</select></label><label>Location *<select required name="location"><option value="">Select campus location</option>${options(LOCATIONS)}</select></label></div><label>Description *<textarea required name="description" rows="4"></textarea></label></div><div class="form-section"><div class="two-col"><label>Date *<input required name="date" type="date"></label><label>Approximate time<input name="time" type="time"></label></div></div><div class="form-actions"><button type="button" class="btn secondary" onclick="navigate('dashboard')">Cancel</button><button class="btn primary">Submit report</button></div></form></div>`,lost?'Report Lost':'Report Found');}
async function submitReport(event,type){event.preventDefault();const data=new FormData(event.target),payload={itemName:data.get('title'),category:data.get('category'),color:data.get('color'),location:data.get('location'),description:data.get('description'),dateTime:`${data.get('date')}T${data.get('time')||'12:00'}:00`,status:'Active',imageUrl:''};try{await api(type==='LOST'?'/lost-items':'/found-items',{method:'POST',body:JSON.stringify(payload)});await loadItems();alert('Report submitted successfully.');navigate('reports');}catch(error){alert('Backend is unavailable. Start it and try again.');}}
function reports(){return shell(`<div class="section-heading"><div><span class="eyebrow">Your activity</span><h2>All Reports</h2></div>${status()}</div><div class="item-grid">${items().map(card).join('')||empty('No reports yet','Create a report to add it here.')}</div>`,'My Reports');}
function settings(){return shell(`<div class="page-intro"><span class="eyebrow">Account</span><h2>Settings</h2></div><div class="settings-grid"><div class="form-card"><h3>Profile</h3><label>Name<input value="${esc(currentUser?.name||'Student')}"></label><label>Email<input value="${esc(currentUser?.email||'student@example.com')}" disabled></label></div><div class="form-card"><h3>Security</h3><p class="dsa-note">Google accounts are verified server-side before sign-in.</p></div></div>`,'Settings');}
function detail(key){const item=items().find(i=>String(i.id)===decodeURIComponent(key));if(!item)return shell(empty('Item not found','Return to Browse & Search.'),'Item Details');const match=item.type==='LOST'&&item.serverId?`<section class="match-section"><h3>Possible found-item matches</h3><p id="match-note" class="dsa-note">Loading heap-ranked candidates…</p><div id="matches" class="match-list"></div></section>`:'';return shell(`<button class="text-btn" onclick="navigate('browse')">← Back to search</button><div class="details"><div class="details-image">${item.imageUrl?`<img src="${esc(item.imageUrl)}" alt="${esc(item.title)}">`:item.type==='LOST'?'?':'✓'}</div><div class="details-body"><span class="badge ${item.type.toLowerCase()}">${item.type}</span><h2>${esc(item.title)}</h2><p class="lead">${esc(item.description)}</p><dl><div><dt>Category</dt><dd>${esc(item.category)}</dd></div><div><dt>Color</dt><dd>${esc(item.color)}</dd></div><div><dt>Location</dt><dd>${esc(item.location)}</dd></div><div><dt>Date</dt><dd>${esc(item.date)}</dd></div></dl>${match}</div></div>`,'Item Details');}
async function loadMatches(id){const target=document.getElementById('matches');if(!target)return;try{const matches=(await api(`/lost-items/${id}/matches?limit=5`)).filter(m=>m.score>0);document.getElementById('match-note').textContent='Scores use the supplied color, location, keyword scorer and MaxHeap ranking.';target.innerHTML=matches.length?matches.map(m=>`<div class="match-row"><div><strong>${esc(m.item.itemName)}</strong><span>${esc(m.item.category)} · ${esc(m.item.location)}</span></div><b>${Math.round(m.score*100)}% match</b></div>`).join(''):'No meaningful candidates yet.';}catch(error){document.getElementById('match-note').textContent='Could not retrieve matches from the backend.';}}
function empty(title,message){return `<div class="empty"><h3>${esc(title)}</h3><p>${esc(message)}</p></div>`;}
function auth(page){const login=page==='login';return `<main class="auth-page"><div class="auth-brand"><div class="brand-mark">LF</div>Lost & Found</div><div class="auth-card"><span class="eyebrow">Campus platform</span><h1>${login?'Welcome back':'Create your account'}</h1><p>${login?'Sign in to manage reports and find items.':'Use your university email to get started.'}</p>${login?'<div id="google-button" class="google-signin"></div><div class="auth-divider"><span>or use demo sign-in</span></div>':''}<p id="auth-message" class="auth-message"></p><form onsubmit="handleAuth(event,'${login?'login':'signup'}')">${login?'':'<label>Full name<input name="name" required></label>'}<label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label>${login?'':'<label>Confirm password<input name="confirm" type="password" required></label>'}<button class="btn primary full">${login?'Log in':'Create account'}</button></form><div class="auth-switch">${login?'New here?':'Already have an account?'} <button class="text-btn" onclick="navigate('${login?'signup':'login'}')">${login?'Create an account':'Log in'}</button></div></div></main>`;}
function setAuthMessage(message){const node=document.getElementById('auth-message');if(node)node.textContent=message;}
function handleAuth(event,mode){event.preventDefault();const data=new FormData(event.target);if(mode==='signup'&&data.get('password')!==data.get('confirm'))return setAuthMessage('Passwords do not match.');saveUser({name:data.get('name')||data.get('email').split('@')[0],email:data.get('email')});navigate('dashboard');}
async function googleCredential(response){setAuthMessage('Verifying your Google account…');try{saveUser(await api('/auth/google',{method:'POST',body:JSON.stringify({credential:response.credential})}));navigate('dashboard');}catch(error){setAuthMessage('Google sign-in could not be verified. Ensure the backend runs and this origin is authorised in Google Cloud.');}}
function setupGoogle(){const mount=document.getElementById('google-button');if(!mount||!window.google?.accounts?.id)return;if(!googleReady){window.google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:googleCredential,auto_select:false});googleReady=true;}window.google.accounts.id.renderButton(mount,{theme:'outline',size:'large',width:360,text:'signin_with'});}
function render(){if(!currentUser&&!['login','signup'].includes(activePage))activePage='login';let html=activePage==='login'||activePage==='signup'?auth(activePage):activePage==='dashboard'?dashboard():activePage==='browse'?browse():activePage==='report-lost'?reportForm('LOST'):activePage==='report-found'?reportForm('FOUND'):activePage==='reports'?reports():activePage==='settings'?settings():activePage.startsWith('item-')?detail(activePage.slice(5)):dashboard();app.innerHTML=html;if(activePage==='login')setTimeout(setupGoogle,0);if(activePage==='browse')setTimeout(filterItems,0);if(activePage.startsWith('item-')){const item=items().find(i=>String(i.id)===decodeURIComponent(activePage.slice(5)));if(item?.type==='LOST'&&item.serverId)setTimeout(()=>loadMatches(item.serverId),0);}}
window.onGoogleLibraryLoad=setupGoogle;window.addEventListener('hashchange',()=>{activePage=location.hash.slice(1)||(currentUser?'dashboard':'login');render();});render();loadItems().then(()=>{if(currentUser)render();});
